#pragma once

#include <array>
#include <glm/glm.hpp>
#include <memory>
#include <vector>

namespace engine {

    class World;
    struct AABB;

    struct CollisionInfo {
        static constexpr int AXIS_X_MASK = 1;
        static constexpr int AXIS_Y_MASK = 2;
        static constexpr int AXIS_Z_MASK = 4;

        /// @brief The position correction that was applied during the collision resolution, so the AABB stops touching any other AABB.
        glm::vec3 correction{0.f};

        /// @brief The time till the collision happens for all axis with the provided move step.
        /// @note If this is 1.0f for some axis, then there is no collision on that axis.
        ///       If this is < 1.0f The move step was multiplied by this value to reflect
        ///       the collision response. (eg. stopping movement in a obscured direction)
        glm::vec3 t{1.f};

        /// @brief The positions of the AABBs that will be hit after the move step is applied. (for each axis)
        std::array<std::vector<glm::vec3>, 3> hitPositions;

        /// @brief Bitfield indicating which axis has a collision data (0bxyz)
        /// @note You can 'and' this with 1 << axis index to check if there is a collision on that axis.
        /// @example If axisInfo[2].t is smaller than 1, then axis & 1 << 2 will be true. (will check axis z)
        unsigned int axis : 3 = 0b000;

        /// @brief If the AABB is grounded, meaning it is touching the ground.
        bool grounded : 1 = false;

        /// @brief The height that was stepped up (for stairs/slabs). 0 if no step.
        float stepHeight = 0.0f;
    };

    class AABBCollider {
      public:
        AABBCollider(std::shared_ptr<AABB> aabb, float stepHeight = 0.0f);

        /// @brief Sets the world for this collider.
        void setWorld(std::shared_ptr<World> world);

        /// @brief Sets the AABB that will be checked for collisions against the world.
        void setAABB(std::shared_ptr<AABB> aabb);

        /// @brief Checks if the AABB collides with any blocks in the world.
        /// @param moveStep The move delta or velocity of the AABB. The components will be modified to reflect the collision response.
        /// @param position The position of the AABB feet. Based on this surrounding AABBs will be generated.
        /// @param dt The delta time since the last collision check.
        CollisionInfo collide(glm::vec3& moveStep, const glm::vec3& position, float dt);

      protected:
        /// @brief The box around the AABB that will be generated, thus checked for collisions against the world.
        /// @note This box is generated by taking the AABB and adding the amount of blocks in given direction to all sides.
        static constexpr glm::vec3 s_checkBox{1.5f};
        static constexpr float s_epsGap = std::numeric_limits<float>::epsilon() * 64.0f;

        std::shared_ptr<World> m_world = nullptr;
        std::shared_ptr<AABB> m_aabb;
        float m_stepHeight;
        float m_height;

        std::vector<AABB> m_aabbCache;
        glm::ivec3 m_lastPosition;
        // TODO remove or implement. Should be indicating the direction/velocity for which the AABB cache is generated.
        glm::vec3 m_cacheDirection;

        float m_stepUpCooldown = 0.0f;


        struct SweptResult {
            float time;
            int axis;
            const AABB* bb;
        };

        void updateAABBCache(const glm::vec3& velocity, const glm::vec3& position);
        SweptResult swept(const glm::vec3& velocity, const AABB& other) const;
        float swept1D(int axis, float velocity, const AABB& other);

        /// @brief Attempts to step up when hitting a horizontal obstacle
        /// @param horizontalMove The horizontal movement vector on the colliding axis
        /// @param collidingBB The AABB that was collided with
        /// @return The step height if stepping is possible, -1.0f otherwise
        float tryStepUp(const glm::vec3& horizontalMove, const AABB* collidingBB);
    };

}  // namespace engine