#pragma once

#include "Registry.h"
#include "block/Block.h"
#include "block/Geometry.h"


namespace engine {
    class RegistryManager {
      public:
        using BlockRegistryT =
            Registry<Block, RegistryStoragePolicy::ByPointer, RegistryStoragePolicy::UserProvidedID>;
        using GeometryRegistryT =
            Registry<Geometry, RegistryStoragePolicy::ByValue, RegistryStoragePolicy::AutoGeneratedID>;

        static BlockRegistryT& Blocks();
        static GeometryRegistryT& Geometries();
    };
}  // namespace engine