#pragma once


#include <data/Registry.h>
#include <data/RegistryManager.h>


#include "../block/MultiBlockCombination.h"


class MyRegistryManager : public engine::RegistryManager {
  public:
    using MultiBlockCombinationRegistryT = engine::Registry<
        MultiBlockCombination,
        engine::RegistryStoragePolicy::ByValue,
        engine::RegistryStoragePolicy::AutoGeneratedID>;

    static MultiBlockCombinationRegistryT& MultiBlockCombinations() {
        static std::decay_t<MultiBlockCombinationRegistryT> multiBlockCombinations;
        return multiBlockCombinations;
    }
};