name: Static analysis

permissions:
  pull-requests: write
  contents: read


on: [push]

jobs:
  static-check:
    name: Static analysis Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Check commit message and exit if needed
      run: |
        MSG=$(git log -1 --pretty=%B)
        echo "Commit message: $MSG"
        if [[ "$MSG" != *cppcheck* ]]; then
            echo "No 'cppcheck' in commit message. Skipping job."
            exit 78  # Special neutral exit code (doesn't fail the job)
        fi

    - name: Configure CMake
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_DEPENDENCIES=OFF -B build -S .

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
      
    - name: Run cppcheck
      run: |
        cppcheck --enable=all \
                --inconclusive \
                --std=c++20 \
                --quiet \
                --suppress=missingIncludeSystem \
                --project=build/compile_commands.json 2> cppcheck_result.txt
        cat cppcheck_result.txt


    - name: Post comment on PR
      run: node .github/scripts/postCPPCheck.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT: cppcheck_result.txt