#pragma once

#include <glm/glm.hpp>
#include <memory>
#include "AABB.h"

namespace engine {

    class World;

    class AABBCollider {
      public:
        AABBCollider(const AABB& aabb, float stepHeight = 0.0f);

        /// @brief Sets the world for this collider.
        void setWorld(std::shared_ptr<World> world);

        /// @brief Sets the AABB that will be checked for collisions against the world.
        void setAABB(const AABB& aabb);

        /// @brief Checks if the AABB collides with any blocks in the world.
        /// @param velocity The velocity of the AABB. After the function call, this will be modified to
        ///                reflect the collision response. (eg. stopping movement in a obscured direction)
        /// @param position The position of the AABB feet. After the function call, this will be modified to
        ///                reflect the collision response. (eg. stepping up)
        /// @note This function should be called for each axis, so 3 times for x, y and z.
        /// @note The position should be the feet position of the AABB, eg the bottom of the AABB.
        bool collide(glm::vec3& velocity, glm::vec3& position);

      protected:
        /// @brief The box around the AABB that will be generated, thus checked for collisions against the world.
        /// @note This box is generated by taking the AABB and adding the amount of blocks in given direction to all sides.
        static constexpr glm::ivec3 s_checkBox{1, 1, 1};

        std::shared_ptr<World> m_world = nullptr;
        AABB m_aabb;
        float m_stepHeight;
        float m_height;

        std::vector<AABB> m_aabbCache;  // Cached world AABBs around the AABB.
        glm::ivec3
            m_lastPosition;  // The last position of the AABB thus where the aabbCache is generated.
        glm::vec3 m_cacheDirection;  // The direction in which the AABB cache is generated.


        struct SweptResult {
            float time;
            int axis;
        };
        void updateAABBCache(const glm::vec3& velocity, const glm::vec3& position);
        SweptResult swept(glm::vec3& velocity, const AABB& other);
    };

}  // namespace engine